version: '3.8'

services:
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_DB_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_DB_PASSWORD}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_DB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_DB_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo