version: '3.8'

services:
  
  catalog:
    container_name: catalog
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: services/Catalog/Catalog
      dockerfile: Dockerfile
    ports:
      - "5184:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings__ConnectionString: "mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo:27017"
      Logging__LogLevel__Default: Information
    depends_on:
      - mongo

  cart:
    container_name: cart
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: services/Cart/Cart
      dockerfile: Dockerfile
    ports:
      - "5277:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CacheSettings__ConnectionString: "redis:6379"
      CacheSettings__Password: "${REDIS_PASSWORD}"
      Logging__LogLevel__Default: Information
    depends_on:
      - redis