version: '3.8'

services:
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_DB_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_DB_PASSWORD}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_DB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_DB_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
  
  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander
    ports:
      - "8082:8081"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    depends_on:
      - redis
  
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine
    ports:
      - "8083:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data:rw
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8084:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWORD}"
    depends_on:
      - postgres

volumes:
  portainer_data:
  pgadmin_data: