version: '3.8'

services:
  
  catalog:
    container_name: catalog
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: services/Catalog/Catalog/Dockerfile
    ports:
      - "5184:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings__ConnectionString: "mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo:27017"
    depends_on:
      - mongo

  cart:
    container_name: cart
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: services/Cart/Cart/Dockerfile
    ports:
      - "5277:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development