version: '3.8'

services:
  
  catalog:
    container_name: catalog
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: services/Catalog/Catalog/Dockerfile
    ports:
      - "5184:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      DatabaseSettings__ConnectionString: "mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo:27017"
    depends_on:
      - mongo

  cart:
    container_name: cart
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: services/Cart/Cart/Dockerfile
    ports:
      - "5277:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      CacheSettings__ConnectionString: "redis:6379"
      CacheSettings__Password: "${REDIS_PASSWORD}"
      GrpcSettings__DiscountUrl: http://discount-grpc
    depends_on:
      - redis
      - discount-grpc
  
  discount:
    container_name: discount
    image: ${DOCKER_REGISTRY}discount
    build:
      context: .
      dockerfile: services/Discount/Discount/Dockerfile
    ports:
      - "5161:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      DatabaseSettings__ConnectionString: "Server=postgres;Port=5432;Database=discount;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
    depends_on:
      - postgres

  discount-grpc:
    container_name: discount-grpc
    image: ${DOCKER_REGISTRY}discount-grpc
    build:
      context: .
      dockerfile: services/Discount/Discount.gRPC/Dockerfile
    ports:
      - "5192:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      DatabaseSettings__ConnectionString: "Server=postgres;Port=5432;Database=discount;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
      
  orders:
    container_name: orders
    image: ${DOCKER_REGISTRY}orders
    build:
      context: .
      dockerfile: services/Orders/Orders.REST/Dockerfile
    ports:
      - "5098:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      DatabaseSettings__SqlConnectionString: "${MSSQL_CONN_STRING}"
