---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: orcuslab.azurecr.io/final_project_webui
          ports:
            - containerPort: 80
          env:
            - name: Logging__LogLevel__Default
              value: "Information"
            - name: REACT_APP_CATALOG_SERVICE_URL
              value: "https://ecommerce.az.orcuslab.com/api/catalog/api/v1/catalog"
            - name: REACT_APP_CART_SERVICE_URL
              value: "https://ecommerce.az.orcuslab.com/api/cart/api/v1/cart"
            - name: REACT_APP_AUTH0_DOMAIN
              value: "dev-wmjl5tm2.us.auth0.com"
            - name: REACT_APP_AUTH0_CLIENT_ID
              value: "FMeJHSqsHUm6ajT8xypQjlEAgoQH7WHj"
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: ASPNETCORE_ENVIRONMENT
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: webui
