---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: final-project
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ecommerce.az.orcuslab.com
      secretName: finalproject-tls
  rules:
    - host: ecommerce.az.orcuslab.com
      http:
        paths:
          - path: /cart(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 5000
          - path: /catalog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 5000
          - path: /orders(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 5000
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: webui
                port:
                  number: 5000
