---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: orcuslab.azurecr.io/final_project_cart
          ports:
            - containerPort: 80
          env:
            - name: Logging__LogLevel__Default
              value: "Information"
            - name: CacheSettings__ConnectionString
              value: "redis:6379"
            - name: GrpcSettings__DiscountUrl
              value: "http://discount:5000"
            - name: Messaging__ConnectionString
              value: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672"
            - name: CacheSettings__Password
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: REDIS_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: ASPNETCORE_ENVIRONMENT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: RABBITMQ_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: cart
