---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: SQL_SERVER_PASS
          volumeMounts:
            - name: sqlserver
              mountPath: /var/opt/mssql
      volumes:
        - name: sqlserver
          persistentVolumeClaim:
            claimName: sqlserver
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    app: sqlserver
