---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: orcuslab.azurecr.io/final_project_orders
          ports:
            - containerPort: 80
          env:
            - name: Messaging__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: RABBITMQ_CONN_STRING
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: ASPNETCORE_ENVIRONMENT
            - name: Logging__LogLevel__Default
              value: "Information"
            - name: ConnectionStrings__SqlConnectionString
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: MSSQL_CONN_STRING
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: RABBITMQ_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: orders
