---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: orcuslab.azurecr.io/final_project_catalog
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Logging__LogLevel__Default
              value: "Information"
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo:27017"
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: MONGO_DB_USER
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: final-project-secrets
                  key: MONGO_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: catalog
